# values held fixed unless overridden
baseline: &base
  epochs:             40          # or 200 if time permits
  batch_size:         128
  backbone_kind:      vit
  vit_embed_dim:      512
  vit_depth:          4
  num_heads:          8           # 256 // 64
  coupling_layers:    10
  ratio_M:            4           # 4 channel : 1 spatial
  spatial_mode:       mix
  masking_mode:       pairing
  actnorm:            false
  invertible_dense:   false
  precision:          tf32        # default precision: tf32 on CUDA
  grad_checkpoint:    false       # memory-saving option

# A1 — ViT depth (Fig 2b)
vit_depth_sweep:
  <<: *base
  vit_depth: [1, 2, 3, 4, 5, 6]

# A2 — Backbone comparison (Fig 2a, toy configs)
backbone_sweep:
  <<: *base
  backbone_kind: ["vit", "cnn"]
  cnn_embed_dim: 512
  cnn_block_depth: 4

# A3 — Channel : Spatial coupling (Fig 4)
coupling_type_sweep:
  <<: *base
  ratio_M: [-1, 0, 1, 2, 3, 4, 5]             # -1=all spatial, 0=all channel
  spatial_mode: ["row", "column", "checkerboard", "mix"]

# A4 — Mask vs Pair split (Table 2a)
masking_pairing_sweep:
  <<: *base
  masking_mode: ["pairing", "masking"]
  ratio_M: [4]

# A5 — ActNorm × Invertible dense (Table 2b)
norm_dense_sweep:
  <<: *base
  actnorm: [true, false]
  invertible_dense: [true, false]