# Derived from a Big Vision JET configuration and substantially modified;
# Copyright 2024 Big Vision Authors, Apache-2.0. See NOTICE.
# batch_size is the paper's global batch; set batch_size x grad_accum_steps x world size to it.
num_epochs: 500
batch_size: 4096
input:
  dataset: imagenet64_tfds
  class_subset: 0:100
  input_size: [64, 64]
  num_classes: 100
  num_workers: 16
model: {width: 1024, depth: 24, mlp_dim: 4096, num_heads: 16, num_mixtures: 1024, grad_checkpoint: true}
image: {ar_dim: 48}
flow: {block_depth: 4, emb_dim: 512, num_heads: 8}
optimizer: {lr: 0.001}
schedule: {warmup_percent: 0.1}
training: {noise_scale: 64.0}
sampling: {temperature: 0.94, cfg_weight: 3.0}
eval: {val_every_epochs: 5}
logging: {advanced_metrics: true}
wandb:
  project: jetformer-imagenet-64
  run_name: B-64
  tags: [imagenet, 64x64, B]
