vocab_size: 32000
d_model: 128
n_heads: 8
n_kv_heads: 1
n_layers: 4
d_ff: 512
max_seq_len: 64
num_mixtures: 4
dropout: 0.1
jet_depth: 2
jet_block_depth: 2
jet_emb_dim: 512
jet_num_heads: 8
patch_size: 16
image_ar_dim: 128
num_classes: null
class_token_length: 16
latent_projection: null
latent_proj_matrix_path: null
batch_size: 8
learning_rate: 0.001
num_epochs: 100
text_loss_weight: 0.0025
image_loss_weight: 1.0
max_samples: 10000
use_cogvlm_captions: true
min_resolution: 256
num_workers: 4
noise_std: 0.1
ignore_pad: false
rgb_sigma0: 64.0
rgb_sigma_final: 3.0
latent_noise_std: 0.3
cfg_drop_prob: 0.1
cfg_strength: 4.0