vocab_size: 32000
d_model: 64
n_heads: 4
n_layers: 2
d_ff: 512
max_seq_len: 64
num_mixtures: 4
dropout: 0.1
jet_depth: 1
jet_block_depth: 2
jet_emb_dim: 512
jet_num_heads: 8
patch_size: 16
batch_size: 8
learning_rate: 0.0001
num_epochs: 10
text_loss_weight: 1.0
image_loss_weight: 1.0
max_samples: 10000
use_cogvlm_captions: true
min_resolution: 512
num_workers: 4
noise_std: 0.1
ignore_pad: false