vocab_size: 32000
d_model: 512
n_heads: 8
n_layers: 9
d_ff: 1024
max_seq_len: 64
num_mixtures: 72 
dropout: 0.1
jet_depth: 8
jet_block_depth: 4
jet_emb_dim: 512
jet_num_heads: 8
patch_size: 16
batch_size: 8
learning_rate: 0.001
num_epochs: 1
text_loss_weight: 0.0025
image_loss_weight: 1.0
max_samples: 500000
use_cogvlm_captions: true
min_resolution: 256
num_workers: 4
noise_std: 0.3
ignore_pad: false
use_bfloat16_img_head: true
torch_compile: false