vocab_size: 32000
d_model: 32
n_heads: 4
n_kv_heads: 1
n_layers: 1
d_ff: 128
max_seq_len: 32
num_mixtures: 8
dropout: 0.1

jet_depth: 1
jet_block_depth: 1
jet_emb_dim: 64
jet_num_heads: 4
patch_size: 16
image_ar_dim: 32

num_classes: null
class_token_length: 16
latent_projection: null
latent_proj_matrix_path: null

batch_size: 1
learning_rate: 0.0005
num_epochs: 1

max_samples: 32
use_cogvlm_captions: true
min_resolution: 512
num_workers: 2
ignore_pad: false

rgb_sigma0: 64.0
rgb_sigma_final: 3.0
latent_noise_std: 0.3
cfg_drop_prob: 0.1
cfg_strength: 4.0

use_bfloat16_img_head: true
torch_compile: false

